
FinGreen3D: TutorialProg.f90 FinGreen3D.f90 FinGrnExtSubs.f90
	gfortran -o FinGreen3D_Tutorial TutorialProg.f90 FinGreen3D.f90 FinGrnExtSubs.f90 -Wall

### DO NOT remove this line - make depends on it ###

